### ISSUE TITLE
[Solution] Freezing when higher precedence operators come later in the evaluation.

### ISSUE THREAD

**Issue by Splitix** [micahrowell/Micahs_Calculator#1]
**NOTE: This solution doesn't solve this issue, but only helps show you where the problem is. I know you have worked hard on this app and the code shows, so I didnt want to jump in and solve it for you. If you would like more help with this just let me know. **

After looking at the code I noticed that the shuntYardAlg() method is where your problem is happening. I had to review the Shunting Yard to see what exactly was suppose to happen. 

It appears you have an infinite loop going on:

<img width="657" alt="screen shot 2016-12-24 at 3 54 18 pm" src="https://cloud.githubusercontent.com/assets/7977304/21468866/5647cb8e-c9f1-11e6-8483-99d4d619fbc3.png">

I don't know the algorith well enough to solve it but from what I got from it you dont need to empty the operan stack every time. Only when you meet requirements. 

In your case that while loop well keep on running until "operStack" is empty. 

Here is a sample output that is happening when you run 2 + 3 * 3:
>2 is added to the output stack. 
'+' skips the while loop because operStack is empty
'+' is added to operStack
3 is added to the output stack so now the output stack has [2, 3].
'*' enters the while loop because operStack has [+] in it.

Here is where it keeps stuck:
>First if statement:  * has a associative of left. So the first part of the if statement is true. 
Second part of the if statement: precedence(in) <= precedence(operStack.peek())
precedence(*) --> 2
precedence(+) --> 1
Therefore 2 well never be less than or equal to 1. So this if statement fails. 
Second if statment fails right away because its not a right. 
While loops starts over because the operStack is not empty. 

Hopefully this helps you find your solution. 

-Joshua

**Comment by micahrowell** [comment]
Fixed, changed the if statements up in the while loop. Thanks for showing me where it was!
