### ISSUE TITLE
Remove/Resize Background image

### ISSUE THREAD

**Issue by Splitix** [micahrowell/Micahs_Calculator#2]
Your background image "calc_app_design" is too large and produces a lot of errors for the openGL

>W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (5600x10240, max=8192x8192)

Until you can resize the image I would remove it for fix those errors.

**Comment by micahrowell** [comment]
I looked up the proper background image size and adjusted accordingly. I also made sure to set the compatibility with other/smaller screen sizes.
